# Site settings
name: Shikai Jin
location: Rice University
github: https://github.com/CryoSky
mail: cryosky@rice.edu
blog: https://www.cryosky.com

baseurl: "/cryosky.github.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

