# Site settings
name: Shikai Jin
location: Rice University
github: https://github.com/CryoSky
email: cryosky@rice.edu
blog: https://www.cryosky.com
#facebook: https://www.facebook.com/
#phone: 1580424XXXX

baseurl: "/cryosky.github.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

